/**
 * @fileoverview TaskDefinition IR → Computation JS Source Transpiler
 *
 * Converts a validated TaskDefinition IR into the JavaScript source code
 * format expected by the computation-system-v4 kernel.
 *
 * The generated code follows the canonical computation pattern:
 *   exports.config = { ... }
 *   exports.process = async function(ctx) { ... }
 *
 * This source is what gets verified by DefaultVerificationPlugin,
 * manifested by ManifestPlugin, and executed by the kernel runtime.
 */

import type { TaskDefinitionIR } from './graphToTaskDefinition';

/**
 * Generate computation JS source from a TaskDefinition IR.
 */
export function taskDefinitionToSource(ir: TaskDefinitionIR): string {
  const lines: string[] = [];

  // ─── Header ────────────────────────────────────────────────
  lines.push(`// Auto-generated by Bulltrackers Task Builder`);
  lines.push(`// Task: ${ir.meta.name}`);
  lines.push(`// Generated: ${new Date().toISOString()}`);
  lines.push(`// DO NOT EDIT — changes will be overwritten on next deploy`);
  lines.push('');

  // ─── exports.config ────────────────────────────────────────
  lines.push('exports.config = {');
  lines.push(`  name: ${JSON.stringify(ir.meta.taskSlug || slugify(ir.meta.name))},`);
  lines.push(`  displayName: ${JSON.stringify(ir.meta.name)},`);

  if (ir.meta.description) {
    lines.push(`  description: ${JSON.stringify(ir.meta.description)},`);
  }

  // Schedule
  if (ir.schedule) {
    lines.push(`  schedule: ${JSON.stringify(ir.schedule)},`);
  }

  // Tags
  if (ir.meta.tags && ir.meta.tags.length > 0) {
    lines.push(`  tags: ${JSON.stringify(ir.meta.tags)},`);
  }

  // Required tables
  const requires: Record<string, { lookback: number; entityField: string }> = {};
  for (const input of ir.inputs) {
    requires[input.dataSource] = {
      lookback: (input as any).lookbackDays || 7,
      entityField: 'user_id',
    };
  }
  lines.push(`  requires: ${JSON.stringify(requires, null, 4)},`);

  // Skills (always include lib for transform nodes)
  const hasTransforms = ir.steps.some(s => s.type === 'bt:transform');
  if (hasTransforms) {
    const libModules = [...new Set(
      ir.steps
        .filter(s => s.type === 'bt:transform' && s.config?.libraryModule)
        .map(s => s.config!.libraryModule as string)
    )];
    lines.push(`  skills: ['lib'],`);
    lines.push(`  lib: ${JSON.stringify(libModules)},`);
  }

  // Policies
  if (ir.policies) {
    lines.push(`  policies: ${JSON.stringify(ir.policies)},`);
  }

  // User config
  const userConfig: Record<string, unknown> = {};
  for (const step of ir.steps) {
    if (step.config?.parameters) {
      userConfig[`step_${step.id}`] = step.config.parameters;
    }
  }
  if (Object.keys(userConfig).length > 0) {
    lines.push(`  userConfig: ${JSON.stringify(userConfig, null, 4)},`);
  }

  // Task builder metadata (for round-trip reconstruction)
  lines.push(`  _taskBuilder: {`);
  lines.push(`    taskId: ${JSON.stringify(ir.meta.taskId || null)},`);
  lines.push(`    version: ${JSON.stringify(ir.meta.version || null)},`);
  lines.push(`    templateId: ${JSON.stringify(ir.meta.templateId || null)},`);
  lines.push(`  },`);

  lines.push('};');
  lines.push('');

  // ─── exports.process ───────────────────────────────────────
  lines.push('exports.process = async function(ctx) {');
  lines.push('  const results = {};');
  lines.push('');

  // Data input reads
  for (const input of ir.inputs) {
    const varName = sanitizeVarName(input.key);
    const lookback = (input as any).lookbackDays || 7;
    lines.push(`  // Data Source: ${input.label}`);
    lines.push(`  const ${varName} = ctx.dataSlice(${JSON.stringify(input.dataSource)}, ${lookback});`);
    lines.push('');
  }

  // Processing steps
  for (const step of ir.steps) {
    const stepVar = sanitizeVarName(`step_${step.id}`);
    lines.push(`  // Step: ${step.name}`);

    if (step.type === 'bt:transform') {
      const mod = step.config?.libraryModule as string || 'unknown';
      const fn = step.config?.functionName as string || 'process';
      const inputRef = resolveStepInput(step, ir);
      lines.push(`  const ${stepVar} = ctx.lib.${mod}.${fn}(${inputRef});`);
    } else if (step.type === 'bt:condition') {
      const inputRef = resolveStepInput(step, ir);
      const op = step.config?.operator || '>';
      const field = step.config?.compareField || 'value';
      const value = step.config?.compareValue ?? 0;
      lines.push(`  const ${stepVar} = ${inputRef}${field ? `.${field}` : ''} ${op} ${JSON.stringify(value)};`);
    } else if (step.type === 'bt:aggregation') {
      const inputRef = resolveStepInput(step, ir);
      const operation = step.config?.operation || 'reduce';
      const reduceField = step.config?.reduceField || '';
      const reduceFunc = step.config?.reduceFunction || 'sum';

      if (operation === 'reduce' && reduceField) {
        if (reduceFunc === 'sum') {
          lines.push(`  const ${stepVar} = ${inputRef}.reduce((acc, row) => acc + (row.${reduceField} || 0), 0);`);
        } else if (reduceFunc === 'avg') {
          lines.push(`  const ${stepVar} = ${inputRef}.length > 0 ? ${inputRef}.reduce((acc, row) => acc + (row.${reduceField} || 0), 0) / ${inputRef}.length : 0;`);
        } else {
          lines.push(`  const ${stepVar} = ${inputRef}; // aggregation: ${operation}/${reduceFunc}`);
        }
      } else {
        lines.push(`  const ${stepVar} = ${inputRef}; // aggregation: ${operation}`);
      }
    } else {
      const inputRef = resolveStepInput(step, ir);
      lines.push(`  const ${stepVar} = ${inputRef}; // type: ${step.type}`);
    }
    lines.push('');
  }

  // Outputs
  for (const output of ir.outputs) {
    const inputEdge = resolveOutputInput(output, ir);
    lines.push(`  // Output: ${output.label || output.target}`);
    lines.push(`  results[${JSON.stringify(output.target)}] = ${inputEdge};`);
  }

  lines.push('');
  lines.push('  return results;');
  lines.push('};');

  return lines.join('\n');
}

// ─── Helpers ───────────────────────────────────────────────────

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

function sanitizeVarName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .replace(/^[0-9]/, '_$&');
}

function resolveStepInput(
  step: TaskDefinitionIR['steps'][number],
  ir: TaskDefinitionIR,
): string {
  if (step.inputs && step.inputs.length > 0) {
    const sourceId = step.inputs[0].source;

    // Check if source is a data input node
    const matchingInput = ir.inputs.find(i => i.nodeId === sourceId);
    if (matchingInput) {
      return sanitizeVarName(matchingInput.key);
    }

    // Check if source is another step
    const matchingStep = ir.steps.find(s => s.nodeId === sourceId);
    if (matchingStep) {
      return sanitizeVarName(`step_${matchingStep.id}`);
    }
  }
  return 'ctx.data';
}

function resolveOutputInput(
  output: TaskDefinitionIR['outputs'][number],
  ir: TaskDefinitionIR,
): string {
  // Find the edge pointing to this output node
  const uiEdges = ir.ui?.graph?.edges || [];
  const incomingEdge = uiEdges.find(e => e.target === output.nodeId);

  if (incomingEdge) {
    const sourceId = incomingEdge.source;

    const matchingInput = ir.inputs.find(i => i.nodeId === sourceId);
    if (matchingInput) return sanitizeVarName(matchingInput.key);

    const matchingStep = ir.steps.find(s => s.nodeId === sourceId);
    if (matchingStep) return sanitizeVarName(`step_${matchingStep.id}`);
  }

  return 'results';
}
