import type { IBoard } from "../../lib";

const defineBoardTemplate = (board: unknown): IBoard => board as IBoard;

export const SYSTEM_HEALTH_TEMPLATE = defineBoardTemplate({
	id: "tutorial-system-health",
	app_id: "bulltrackers",
	version: [1, 0, 0],
	created_at: {
		secs_since_epoch: Math.floor(Date.now() / 1000),
		nanos_since_epoch: 0,
	},
	updated_at: {
		secs_since_epoch: Math.floor(Date.now() / 1000),
		nanos_since_epoch: 0,
	},
	nodes: {
		"node-scheduled-trigger": {
			id: "node-scheduled-trigger",
			name: "trigger-scheduled",
			friendly_name: "Morning Schedule Server Trigger",
			start: true,
			coordinates: [100, 100, 0],
			pins: {
				"out-exec": {
					id: "out-exec",
					name: "Execute",
					pin_type: "Output",
					data_type: "Execution",
					dynamic: false,
					depends_on: [],
					connected_to: ["in-exec-fetch"],
					index: 1,
				},
			},
		},
		"node-fetch-status": {
			id: "node-fetch-status",
			name: "ds-dashboard-data",
			friendly_name: "Fetch System Health Status",
			coordinates: [500, 100, 0],
			pins: {
				"in-exec-fetch": {
					id: "in-exec-fetch",
					name: "Execute",
					pin_type: "Input",
					data_type: "Execution",
					dynamic: false,
					depends_on: [],
					connected_to: ["out-exec"],
					index: 1,
				},
				"out-exec-fetch": {
					id: "out-exec-fetch",
					name: "Success",
					pin_type: "Output",
					data_type: "Execution",
					dynamic: false,
					depends_on: [],
					connected_to: ["in-exec-condition"],
					index: 1,
				},
				"out-data": {
					id: "out-data",
					name: "System Status Object",
					pin_type: "Output",
					data_type: "Struct",
					dynamic: false,
					depends_on: [],
					connected_to: ["in-condition-data", "in-notify-data"],
					index: 2,
				},
			},
		},
		"node-condition": {
			id: "node-condition",
			name: "logic-condition",
			friendly_name: "Check if System Operational",
			coordinates: [900, 100, 0],
			pins: {
				"in-exec-condition": {
					id: "in-exec-condition",
					name: "Execute",
					pin_type: "Input",
					data_type: "Execution",
					dynamic: false,
					depends_on: [],
					connected_to: ["out-exec-fetch"],
					index: 1,
				},
				"in-condition-data": {
					id: "in-condition-data",
					name: "Status Result",
					pin_type: "Input",
					data_type: "Struct",
					dynamic: false,
					depends_on: [],
					connected_to: ["out-data"],
					index: 2,
				},
				"out-exec-true": {
					id: "out-exec-true",
					name: "Operational",
					pin_type: "Output",
					data_type: "Execution",
					dynamic: false,
					depends_on: [],
					connected_to: ["in-exec-notify"],
					index: 1,
				},
				"out-exec-false": {
					id: "out-exec-false",
					name: "Degraded",
					pin_type: "Output",
					data_type: "Execution",
					dynamic: false,
					depends_on: [],
					connected_to: [],
					index: 2,
				},
			},
		},
		"node-notify": {
			id: "node-notify",
			name: "lib-notifications",
			friendly_name: "Send Email Template: System Ok",
			coordinates: [1300, 100, 0],
			pins: {
				"in-exec-notify": {
					id: "in-exec-notify",
					name: "Execute",
					pin_type: "Input",
					data_type: "Execution",
					dynamic: false,
					depends_on: [],
					connected_to: ["out-exec-true"],
					index: 1,
				},
				"in-notify-data": {
					id: "in-notify-data",
					name: "Telemetry Context",
					pin_type: "Input",
					data_type: "Struct",
					dynamic: false,
					depends_on: [],
					connected_to: ["out-data"],
					index: 2,
				},
			},
		},
	},
	comments: {},
	refs: {},
	edges: {
		"edge-1": {
			id: "edge-1",
			from_node: "node-scheduled-trigger",
			from_pin: "out-exec",
			to_node: "node-fetch-status",
			to_pin: "in-exec-fetch",
		},
		"edge-2": {
			id: "edge-2",
			from_node: "node-fetch-status",
			from_pin: "out-exec-fetch",
			to_node: "node-condition",
			to_pin: "in-exec-condition",
		},
		"edge-3": {
			id: "edge-3",
			from_node: "node-fetch-status",
			from_pin: "out-data",
			to_node: "node-condition",
			to_pin: "in-condition-data",
		},
		"edge-4": {
			id: "edge-4",
			from_node: "node-condition",
			from_pin: "out-exec-true",
			to_node: "node-notify",
			to_pin: "in-exec-notify",
		},
		"edge-5": {
			id: "edge-5",
			from_node: "node-fetch-status",
			from_pin: "out-data",
			to_node: "node-notify",
			to_pin: "in-notify-data",
		},
	},
	variables: {},
	layers: {},
});
